Added architecture check

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -64,6 +64,17 @@ jobs:
   - script: python -m pip install --upgrade pip
     displayName: 'Updating pip'
 
+  - bash: |
+      TEST_ARCH=$(python -c "import struct; print(struct.calcsize('P') * 8)")
+      if [ $TEST_ARCH -eq $SYS_ARCH ]; then
+          echo "Correct architecture"
+      else
+          echo "Architecture check failed"
+          exit 1
+      fi
+    env:
+      SYS_ARCH: $(architecture)
+
   - script: |
       pip install -r requirements.txt
       pip install -r build_tools/azure/requirements.txt
